spring:
  cloud:
    gateway:
      routes:
        - id: file-service
          uri: http://file-service:8081
        - id: metadata-service
          uri: http://metadata-service:8082
        - id: share-service
          uri: http://metadata-service:8082
        - id: user-service
          uri: http://user-service:8083
        - id: activity-service
          uri: http://activity-service:8084
        - id: thumbnail-service
          uri: http://thumbnail-service:8085
        - id: search-service
          uri: http://search-service:8086
  
  data:
    redis:
      host: redis
      port: 6379
